### ISSUE TITLE
Unable to build n1474335 (babel-data/corejs3-shipped-proposals module build fail)

### ISSUE THREAD

**Issue by cleancopy** [gchq/CyberChef#1035]
I'm unable to build n1474335 on nodev14.2.0 with npm 6.14.4 grunt grunt@1.1.0
errors as follows and npm list below that

    ERROR in ./src/web/index.js
    Module build failed (from ./node_modules/babel-loader/lib/index.js):
    Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
    Require stack:
    - /CyberChef/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
    - /CyberChef/node_modules/@babel/preset-env/lib/index.js
    - /CyberChef/node_modules/@babel/core/lib/config/files/plugins.js
    - /CyberChef/node_modules/@babel/core/lib/config/files/index.js
    - /CyberChef/node_modules/@babel/core/lib/index.js
    - /CyberChef/node_modules/babel-loader/lib/index.js
    - /CyberChef/node_modules/loader-runner/lib/loadLoader.js
    - /CyberChef/node_modules/loader-runner/lib/LoaderRunner.js
    - /CyberChef/node_modules/webpack/lib/NormalModule.js
    - /CyberChef/node_modules/webpack/lib/NormalModuleFactory.js
    - /CyberChef/node_modules/webpack/lib/Compiler.js
    - /CyberChef/node_modules/webpack/lib/webpack.js
    - /CyberChef/Gruntfile.js
    - /CyberChef/node_modules/grunt/lib/grunt/task.js
    - /CyberChef/node_modules/grunt/lib/grunt.js
    - /usr/local/lib/node_modules/grunt-cli/bin/grunt
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
      at Function.Module._load (internal/modules/cjs/loader.js:890:27)
      at Module.require (internal/modules/cjs/loader.js:1080:19)
      at require (internal/modules/cjs/helpers.js:72:18)
      at Object.<anonymous> (/CyberChef/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js:10:55)
      at Module._compile (internal/modules/cjs/loader.js:1176:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
      at Module.load (/CyberChef/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
      at Function.Module._load (internal/modules/cjs/loader.js:929:14)
      at Module.require (internal/modules/cjs/loader.js:1080:19)
      at require (internal/modules/cjs/helpers.js:72:18)
      at Object.<anonymous> (/CyberChef/node_modules/@babel/preset-env/lib/index.js:29:44)
      at Module._compile (internal/modules/cjs/loader.js:1176:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
      at Module.load (/CyberChef/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
      at Function.Module._load (internal/modules/cjs/loader.js:929:14)
      at Module.require (internal/modules/cjs/loader.js:1080:19)
      at require (internal/modules/cjs/helpers.js:72:18)
      at requireModule (/CyberChef/node_modules/@babel/core/lib/config/files/plugins.js:165:12)
      at loadPreset (/CyberChef/node_modules/@babel/core/lib/config/files/plugins.js:83:17)
      at createDescriptor (/CyberChef/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
      at /CyberChef/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
      at Array.map (<anonymous>:null:null)
      at createDescriptors (/CyberChef/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
      at createPresetDescriptors (/CyberChef/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
      at presets (/CyberChef/node_modules/@babel/core/lib/config/config-descriptors.js:47:19)
      at mergeChainOpts (/CyberChef/node_modules/@babel/core/lib/config/config-chain.js:320:26)
      at /CyberChef/node_modules/@babel/core/lib/config/config-chain.js:283:7
      at Generator.next (<anonymous>:null:null)
      at buildRootChain (/CyberChef/node_modules/@babel/core/lib/config/config-chain.js:90:27)
      at buildRootChain.next (<anonymous>:null:null)
      at loadPrivatePartialConfig (/CyberChef/node_modules/@babel/core/lib/config/partial.js:95:62)
      at loadPrivatePartialConfig.next (<anonymous>:null:null)
      at Function.<anonymous> (/CyberChef/node_modules/@babel/core/lib/config/partial.js:120:25)
      at Generator.next (<anonymous>:null:null)
      at evaluateSync (/CyberChef/node_modules/gensync/index.js:244:28)
      at Function.sync (/CyberChef/node_modules/gensync/index.js:84:14)
      at Object.<anonymous> (/CyberChef/node_modules/@babel/core/lib/config/index.js:41:61)
      at Object.<anonymous> (/CyberChef/node_modules/babel-loader/lib/index.js:144:26)
      at Generator.next (<anonymous>:null:null)
      at asyncGeneratorStep (/CyberChef/node_modules/babel-loader/lib/index.js:3:103)
      at _next (/CyberChef/node_modules/babel-loader/lib/index.js:5:194)
      at /CyberChef/node_modules/babel-loader/lib/index.js:5:364
      at new Promise (<anonymous>:null:null)
      at Object.<anonymous> (/CyberChef/node_modules/babel-loader/lib/index.js:5:97)
      at Object._loader (/CyberChef/node_modules/babel-loader/lib/index.js:224:18)
      at Object.loader (/CyberChef/node_modules/babel-loader/lib/index.js:60:18)
      at Object.<anonymous> (/CyberChef/node_modules/babel-loader/lib/index.js:55:12)
    ℹ ｢wdm｣: Failed to compile.

+-- @babel/core@7.8.7
+-- @babel/plugin-transform-runtime@7.8.3
+-- @babel/polyfill@7.8.7
+-- @babel/preset-env@7.8.7
+-- @babel/runtime@7.8.7
+-- arrive@2.4.1
+-- autoprefixer@9.7.4
+-- avsc@5.4.19
+-- babel-eslint@10.1.0
+-- babel-loader@8.0.6
+-- babel-plugin-dynamic-import-node@2.3.0
+-- babel-plugin-transform-builtin-extend@1.1.2
+-- bcryptjs@2.4.3
+-- bignumber.js@9.0.0
+-- blakejs@1.1.0
+-- bootstrap@4.4.1
+-- bootstrap-colorpicker@3.2.0
+-- bootstrap-material-design@4.1.2
+-- bson@4.0.3
+-- chi-squared@1.1.0
+-- chromedriver@80.0.1
+-- cli-progress@3.6.0
+-- codepage@1.14.0
+-- colors@1.4.0
+-- copy-webpack-plugin@5.1.1
+-- core-js@3.6.4
+-- crypto-api@0.8.5
+-- crypto-js@4.0.0
+-- css-loader@3.4.2
+-- ctph.js@0.0.5
+-- d3@5.15.0
+-- d3-hexbin@0.2.2
+-- diff@4.0.2
+-- es6-promisify@6.1.0
+-- escodegen@1.14.1
+-- eslint@6.8.0
+-- esm@3.2.25
+-- esmangle@1.0.1
+-- esprima@4.0.1
+-- exif-parser@0.1.12
+-- exports-loader@0.7.0
+-- file-loader@6.0.0
+-- file-saver@2.0.2
+-- geodesy@1.1.3
+-- grunt@1.1.0
+-- grunt-accessibility@6.0.0
+-- grunt-chmod@1.1.1
+-- grunt-concurrent@3.0.0
+-- grunt-contrib-clean@2.0.0
+-- grunt-contrib-connect@2.1.0
+-- grunt-contrib-copy@1.0.0
+-- grunt-contrib-watch@1.1.0
+-- grunt-eslint@22.0.0
+-- grunt-exec@3.0.0
+-- grunt-webpack@3.1.3
+-- grunt-zip@0.18.2
+-- highlight.js@9.18.1
+-- html-webpack-plugin@3.2.0
+-- imports-loader@0.8.0
+-- jimp@0.9.5
+-- jquery@3.4.1
+-- js-crc@0.2.0
+-- js-sha3@0.8.0
+-- jsesc@2.5.2
+-- jsonpath@1.0.2
+-- jsonwebtoken@8.5.1
+-- jsqr@1.2.0
+-- jsrsasign@8.0.12
+-- kbpgp@2.1.13
+-- libbzip2-wasm@0.0.4
+-- libyara-wasm@1.0.1
+-- lodash@4.17.15
+-- loglevel@1.6.7
+-- loglevel-message-prefix@3.0.0
+-- markdown-it@10.0.0
+-- mini-css-extract-plugin@0.9.0
+-- moment@2.24.0
+-- moment-timezone@0.5.28
+-- ngeohash@0.6.3
+-- nightwatch@1.3.4
+-- node-forge@0.9.1
+-- node-md6@0.1.0
+-- node-sass@4.13.1
+-- nodom@2.4.0
+-- notepack.io@2.3.0
+-- nwmatcher@1.4.4
+-- otp@0.1.3
+-- popper.js@1.16.1
+-- postcss-css-variables@0.14.0
+-- postcss-import@12.0.1
+-- postcss-loader@3.0.0
+-- prompt@1.0.0
+-- qr-image@3.2.0
+-- sass-loader@8.0.2
+-- scryptsy@2.1.0
+-- sitemap@6.1.0
+-- snackbarjs@1.1.0
+-- sortablejs@1.10.2
+-- split.js@1.5.11
+-- ssdeep.js@0.0.2
+-- style-loader@1.1.3
+-- svg-url-loader@5.0.0
+-- tesseract.js@2.0.2
+-- ua-parser-js@0.7.21
+-- unorm@1.6.0
+-- url-loader@4.0.0
+-- utf8@3.0.0
+-- vkbeautify@0.99.3
+-- webpack@4.42.0
+-- webpack-bundle-analyzer@3.6.1
+-- webpack-dev-server@3.10.3
+-- webpack-node-externals@1.7.2
+-- worker-loader@2.0.0
+-- xmldom@0.3.0
+-- xpath@0.0.27
+-- xregexp@4.3.0
`-- zlibjs@0.3.1

**Comment by cleancopy** [comment]
Just noticed there's a separate error earlier in the output related to /CyberChef/src/core/lib/FileType :


Running "clean:dev" (clean) task
>> 0 paths cleaned.

Running "clean:config" (clean) task
>> 0 paths cleaned.

Running "exec:generateConfig" (exec) task

--- Regenerating config files. ---
Written operation index.
--- Config scripts finished. ---

internal/modules/run_main.js:54
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/CyberChef/src/core/lib/FileType' imported from /CyberChef/src/core/operations/Gener                                                                                                       ateImage.mjs
    at finalizeResolution (internal/modules/esm/resolve.js:277:11)
    at moduleResolve (internal/modules/esm/resolve.js:658:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:748:11)
    at Loader.resolve (internal/modules/esm/loader.js:97:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:42:40)
    at link (internal/modules/esm/module_job.js:41:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

**Comment by cleancopy** [comment]
Issue was node version too high - resolved by downgrade to v11.15.0
