### ISSUE TITLE
Bug report: <Insert title here>

### ISSUE THREAD

**Issue by WindyOrgUK** [gchq/CyberChef#1158]
**Describe the bug**
Installation on CyberChef fails on Mac OS Catalina during "grunt dev"
repo cloned 30 mins ago
node version v12.14.0 (homebrew installed)

**To Reproduce**
git clone https://github.com/gchq/CyberChef.git
cd CyberChef
npm install
grunt dev

===========================

internal/modules/esm/default_resolve.js:84
  let url = moduleWrapResolve(specifier, parentURL);
            ^

Error: Cannot find module /Users/windy/CyberChef/src/core/lib/FileType imported from /Users/windy/CyberChef/src/core/operations/GenerateImage.mjs
    at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:84:13)
    at Loader.resolve (internal/modules/esm/loader.js:73:33)
    at Loader.getModuleJob (internal/modules/esm/loader.js:147:40)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:41:40)
    at link (internal/modules/esm/module_job.js:40:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Regards
Peter

**Comment by mattnotmitt** [comment]
Hi @WindyOrgUK you should be building with node v10 rather than v12 - try using a tool such as [fnm](https://github.com/Schniz/fnm) to switch versions without replacing the one installed on your system. Hope this helps.

**Comment by WindyOrgUK** [comment]
Perfect, thank you.
That worked.

Regards
Peter
