### ISSUE TITLE
Bug report: ECC PGP key encryption fails

### ISSUE THREAD

**Issue by TerrorFactor** [gchq/CyberChef#1440]
**Describe the bug**
Using an ECC PGP key -generated with CyberChef- fails to encrypt a message (stuck on "baking" indefinitely). RSA keys seem to work without issue. This seems to affect all ECC keys (generated by CyberChef). I am unaware if the problem is related to the generated key, or to the encryption/decryption functionality.

**To Reproduce**
Steps to reproduce the behaviour or a link to the recipe / input used to cause the bug:

1. Generate an ECC key: https://gchq.github.io/CyberChef/#recipe=Generate_PGP_Key_Pair('ECC-256','','','')
2. Use the public key part with "PGP Encrypt" to encrypt a message, example: https://gchq.github.io/CyberChef/#recipe=PGP_Encrypt('-----BEGIN%20PGP%20PUBLIC%20KEY%20BLOCK-----%5CnVersion:%20Keybase%20OpenPGP%20v2.1.15%5CnComment:%20https://keybase.io/crypto%5Cn%5CnxlIEY0oQUBMIKoZIzj0DAQcCAwShl0m1n4YheoAuWw6gYRv2AwfqOO72eC3HjjLJ%5Cn6FBDgYJOaVlJMrwZJXGMm4t6eOkaxI0r5EBBqsDYc6SsIGl8zQDCdgQTEwoAHgUC%5CnY0oQUAIbLwMLCQcDFQoIAh4BAheAAxYCAQIZAQAKCRB749Pifxoqp1EgAP0dRwN8%5Cnz0kC3TkHkgb/FVIiCQ1OoCYSQou171eZ8P4b1wD%2BNkrwlTzn1%2BT4RRJdfZRxTWQ7%5CnofH7GBPgUfG1AVlLr83OUgRjShBQEwgqhkjOPQMBBwIDBMNvsyUtbPaYol8geSOK%5CnliWBhH8rlYfeyG71I4Rxt2W0jIfB2pVINzhEgjWr%2BNrbjRPzz9JJ7VQavTULx/4d%5CnMTzCwAcEGBMKAA8FAmNKEFAFCQ8JnAACGy4AagkQe%2BPT4n8aKqdfIAQZEwoABgUC%5CnY0oQUAAKCRDXBTineFON%2BMUzAQCi3Jo2whZFeqyYi403ogqHT851/AIfx4bN%2B1EG%5Cnhuyl6AD%2BMTIJKHaeVpXdB7FTDFxot2k5diJbnwpqHxWcfq6Qu22/5QEAqyu%2BHuI3%5CnsjzyMK2x5cDE3YZ5PfxNVXQyns7iaKRWtI4A/jmtz9WKazM4X56Sf9Z5d/X/q70n%5CnByPsfGA9OILh%2B/cezlIEY0oQUBMIKoZIzj0DAQcCAwTXS1TWVHeyJQ5tgmw1pG%2BN%5CnxZB1VG8RXtiCQ4E/2W1TnhUMTNjWoYsF3n9JZxNKZuPK6iz5DxpgbKES9HBgNIuL%5CnwsAHBBgTCgAPBQJjShBQBQkDwmcAAhsuAGoJEHvj0%2BJ/GiqnXyAEGRMKAAYFAmNK%5CnEFAACgkQSgxKQyGbPqz7BAD/Z80wAvMRre4besiBrDE5B35sFuIe0DC4UzwS%2BFSw%5CnUKEBAMOfXGOWlIgb46/H/kk9yu11DjFg5G2JVy8zXcxiJ2edmfQA/0zuAZ%2BCAYbq%5CnNzCIuLyh1i9z8iUVr/v7gzzCVbXTy0smAP9kElZBAjG8F%2Bfgeyr3eNXkN3HYfVev%5CnIJYK03CU4ctBjg%3D%3D%5Cn%3DwWNw%5Cn-----END%20PGP%20PUBLIC%20KEY%20BLOCK-----')&input=dGVzdCBtZXNzYWdl

**Expected behaviour**
Get an an encrypted message, that later can be decrypted with the private key.

**Desktop (if relevant, please complete the following information):**
 - OS: Windows 10 (tested on multiple builds/devices)
 - Browser: Edge Version 104.0.1293.47
 - CyberChef version: Version 9.48.0 (also tested on slightly older builds)

**Comment by robo-w** [comment]
Issue is still reproducible in the latest version. Console log shows:

```text
PGP.js:2  Uncaught TypeError: f.pad_and_encrypt is not a function
    at PGP.js:2:564294
    at t._call (PGP.js:2:457841)
    at PGP.js:2:457981
    at u (PGP.js:2:457621)
    at t._fulfill (PGP.js:2:457951)
    at a (PGP.js:2:457202)
    at PGP.js:2:447885
    at PGP.js:2:956059
    at t._call (PGP.js:2:457841)
    at PGP.js:2:457981
```

**Comment by GCHQDeveloper581** [comment]
Resolved by fixing #2267.

Note that invalid keys generated by previous versions will still trigger this error which is inherent to the underlying library.

However newly generated keys will be valid and will operate correctly.
