### ISSUE TITLE
Bug report: <Insert title here>

### ISSUE THREAD

**Issue by Byxs20** [gchq/CyberChef#1559]
**Describe the bug**
This happens when I add multiple methods and then remove one method, he keeps processing, my test is that the unzip method has this problem, when I use the method that detects the file type it does not appear to keep processing

Version : CyberChef_v10.4.0

![Uploading image.gif…]()

`UEsDBBQACAAIAAZUilYAAAAAAAAAACUAAAAVACAATWFnaWMgb2YgRW5jb2RpbmcudHh0VVQNAAdNkTNkTpEzZE2RM2R1eAsAAQT1AQAABBQAAABLy0lMr84wKDCOrzQojc/JzDZOiS/JSI33NUnPTI43L8pMzq7lAgBQSwcIjmX6WicAAAAlAAAAUEsBAhQDFAAIAAgABlSKVo5l+lonAAAAJQAAABUAIAAAAAAAAAAAAKSBAAAAAE1hZ2ljIG9mIEVuY29kaW5nLnR4dFVUDQAHTZEzZE6RM2RNkTNkdXgLAAEE9QEAAAQUAAAAUEsFBgAAAAABAAEAYwAAAIoAAAAAAA==`

**Comment by Byxs20** [comment]
blob:null/7334bf8b-9d8c-4001-95aa-dd05c765c6df:2 Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': Value at index 0 does not have a transferable type.
    at blob:null/7334bf8b-9d8c-4001-95aa-dd05c765c6df:2:1056472
    at u (blob:null/7334bf8b-9d8c-4001-95aa-dd05c765c6df:2:947280)
    at Generator.<anonymous> (blob:null/7334bf8b-9d8c-4001-95aa-dd05c765c6df:2:948635)
    at Generator.next (blob:null/7334bf8b-9d8c-4001-95aa-dd05c765c6df:2:947643)
    at t (blob:null/7334bf8b-9d8c-4001-95aa-dd05c765c6df:2:954445)
    at a (blob:null/7334bf8b-9d8c-4001-95aa-dd05c765c6df:2:954648)
（匿名） @ blob:null/7334bf8b-9d8c-4001-95aa-dd05c765c6df:2
u @ blob:null/7334bf8b-9d8c-4001-95aa-dd05c765c6df:2
（匿名） @ blob:null/7334bf8b-9d8c-4001-95aa-dd05c765c6df:2
（匿名） @ blob:null/7334bf8b-9d8c-4001-95aa-dd05c765c6df:2
t @ blob:null/7334bf8b-9d8c-4001-95aa-dd05c765c6df:2
a @ blob:null/7334bf8b-9d8c-4001-95aa-dd05c765c6df:2
Promise.then（异步）
t @ blob:null/7334bf8b-9d8c-4001-95aa-dd05c765c6df:2
a @ blob:null/7334bf8b-9d8c-4001-95aa-dd05c765c6df:2
（匿名） @ blob:null/7334bf8b-9d8c-4001-95aa-dd05c765c6df:2
（匿名） @ blob:null/7334bf8b-9d8c-4001-95aa-dd05c765c6df:2
（匿名） @ blob:null/7334bf8b-9d8c-4001-95aa-dd05c765c6df:2
（匿名） @ blob:null/7334bf8b-9d8c-4001-95aa-dd05c765c6df:2
Compression.js:2 Uncaught (in promise) Error: End of Central Directory Record not found
    at $ (Compression.js:2:311010)
    at t.Y (Compression.js:2:312340)
    at n.value (Compression.js:2:524223)
    at e.<anonymous> (blob:null/4418fbbf-4390-423b-b3fb-f032172324a8:2:99450)
    at l (blob:null/4418fbbf-4390-423b-b3fb-f032172324a8:2:1772910)
    at Generator.<anonymous> (blob:null/4418fbbf-4390-423b-b3fb-f032172324a8:2:1774265)
    at Generator.next (blob:null/4418fbbf-4390-423b-b3fb-f032172324a8:2:1773273)
    at r (blob:null/4418fbbf-4390-423b-b3fb-f032172324a8:2:1779878)
    at s (blob:null/4418fbbf-4390-423b-b3fb-f032172324a8:2:1780081)

**Comment by Byxs20** [comment]
![image](https://user-images.githubusercontent.com/64669718/232321819-747a469a-e55e-4895-904a-5588bd1297de.gif)
