### ISSUE TITLE
Bug report: Error with crypto-api when trying to use CyberChef as a library

### ISSUE THREAD

**Issue by sergio-calvo-devo** [gchq/CyberChef#561]
### Summary
Greetings,

I'm currently trying to use CyberChef as a library to do some operations on data. I followed the step abd managed to build the node version, but when I try to use it inside my app I always get the following error:
```
const chef = require('../CyberChef/build/node/CyberChef').default;

chef.bake("test", [{"op":"To Hex","args":["Space"]}]).then(r => { console.log(r) })
```
```
{ Error: Cannot find module 'crypto-api/src/crypto-api'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/sergiocalvo/Proyectos/pruebas-js/pocs/cyber-chef/use-lib/app/CyberChef/build/node/CyberChef.js:60:234506)
    at a (/home/sergiocalvo/Proyectos/pruebas-js/pocs/cyber-chef/use-lib/app/CyberChef/build/node/CyberChef.js:21:124)
    at Module.<anonymous> (/home/sergiocalvo/Proyectos/pruebas-js/pocs/cyber-chef/use-lib/app/CyberChef/build/node/CyberChef.js:232:37652)
    at a (/home/sergiocalvo/Proyectos/pruebas-js/pocs/cyber-chef/use-lib/app/CyberChef/build/node/CyberChef.js:21:124)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11) code: 'MODULE_NOT_FOUND' }

```
Is there a problem with dependency loading, or maybe I'm doing something wrong?

Regards, Sergio.

**Comment by n1474335** [comment]
We're currently tracking problems related to crypto-api in https://github.com/gchq/CyberChef/issues/596

The new CyberChef Node API should make this a bit easier.
