### ISSUE TITLE
Bug report: node; SyntaxError: Unexpected identifier crypto-api

### ISSUE THREAD

**Issue by shellliii** [gchq/CyberChef#601]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior or a link to the recipe / input used to cause the bug:
```bash
git clone https://github.com/gchq/cyberchef
cd cyberchef
npm install
grunt node
```
test.js:
```javascript
var chef = require("cyberchef/build/node/CyberChef.js")
console.log(chef)
chef.default.bake("test", [{"op":"To Hex","args":["Space"]}]).then(r => { console.log(r) })
```
`node test.js`

```
cyberchef/node_modules/crypto-api/src/crypto-api.mjs:3
import Has160 from "./hasher/has160";
       ^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:760:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at eval (webpack://CyberChef/external_%22crypto-api/src/crypto-api.mjs%22?:1:18)
    at Object.crypto-api/src/crypto-api.mjs (cyberchef/build/node/CyberChef.js:5377:1)
    at __webpack_require__ (cyberchef/build/node/CyberChef.js:41:30)
    at eval (webpack://CyberChef/./src/core/lib/Hash.mjs?:4:87)

```

**Expected behavior**
test to hex gets executed

**Desktop (if relevant, please complete the following information):**
 - OS: linux
 - Browser node
 - Version v11.15.0

**Comment by d98762625** [comment]
@shellliii please try with `v9.0.5`

**Comment by d98762625** [comment]
Note a couple of things - 

- require("cyberchef") should now be enough, rather than explicit path (there is no 'build' version for node now)
- bake is not async

This code worked for me n v11.15.0 in a new dir:

`npm init` (accept all defaults)
`npm install --save cyberchef`

`vim test.js` (with the following contents)
```javascript
const chef = require("cyberchef")
const d = chef.bake("test", [{"op":"To Hex","args":["Space"]}])
console.log(d)
```

`node test.js`

**Comment by d98762625** [comment]
Closing for now. Please reopen if you have any issues.

**Comment by fjh1997** [comment]
I downgrade to node 10,and it works,the reason is here #596
