### ISSUE TITLE
Feature request: remember scroll position after tab change

### ISSUE THREAD

**Issue by Christilut** [gchq/CyberChef#875]
**Is your feature request related to a problem? Please describe.**
When working with a big piece of text, I sometimes scroll down and copy some text into another tab. When switching back to the first tab, both the input and the output pane is back on top. So I don't know where I was working just now.

**Describe the solution you'd like**
After tab switching, scroll position should be remembered and it should not scroll back to top every time.

**Comment by Vanilna** [comment]
I'd like to help and I have an idea how this can be implemented, but I have a problem with starting a local server.
I've cloned your project, installed dependencies and run npm start, but receive mistake in terminal:
`Running "exec:generateConfig" (exec) task

--- Regenerating config files. ---
Written operation index.
>> internal/modules/esm/default_resolve.js:79
>>   let url = moduleWrapResolve(specifier, parentURL);
>>             ^
>> Error: Cannot find module /mnt/d/coding/open-source/CyberChef/src/core/Operation imported from /mnt/d/coding/open-source/CyberChef/src/core/operations/Lorenz.mjs
>>     at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:79:13)
>>     at Loader.resolve (internal/modules/esm/loader.js:73:33)
>>     at Loader.getModuleJob (internal/modules/esm/loader.js:152:40)
>>     at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:43:40)
>>     at link (internal/modules/esm/module_job.js:42:36) {
>>   code: 'ERR_MODULE_NOT_FOUND'
>> }`

**Comment by FrancoisDuchene** [comment]
Hello ! I would like to work on this feature, i will try to do a PR soon.

**Comment by gabrielatricak** [comment]
Hi, i would like to work on this. Can I be assigned to this?

**Comment by pancholipratham7** [comment]
Hey i want to add this feature can you please assign this to me

**Comment by lion-rion** [comment]
@Christilut
hi, I would like to work on this.
The solution I would like to do is to use JavaScript to memorize the Y-axis coordinates.
I think this issue is still unresolved, may I take charge of it?

**Comment by besalraj30** [comment]
Hi, I would like to work on this.
Could you please assign this to me

**Comment by Lakshya84** [comment]
Hi @Christilut 
I hope you are well. I am here to ask you to give me the opportunity to do so. I hope for a positive reply from your side. I can solve the problem by using JavaScript by memorizing the coordinates of the link that is going to be clicked.

**Comment by jaydaVis04** [comment]
Hi, I’m interested in working on this issue. Is the requested behavior still desired, and is anyone currently working on it? I would plan to identify where tab state is stored, preserve the input/output scroll positions per tab, and add tests where practical.

**Comment by BruceGitHub** [comment]
I tried to investigate this issue (#875), but it appears to be no longer reproducible.

Steps tested:
– Open the Operations panel
– Scroll down
– Switch to Recipe  
– Switch back to Operations

Result:  
The scroll position remains intact.
In the current UI, the Operations panel is not a pinned tab anymore, so switching panels requires clicking it explicitly. Because the panel is not unmounted/remounted, the scroll position is preserved.

This suggests that the issue is no longer applicable due to UI changes introduced after the original report.

If needed, I can provide additional testing details or screenshots.
